// Highlights «О нас»: storytelling stories 1080×1920. Render: node render.mjs o-nas.mjs
export const dir = '../stories-o-nas';
const next = { r: '<span class="arrow">Дальше <i>→</i></span>' };
const story = (o) => ({ size: 'S', corner: '', ...o });
export const specs = [
  story({ out: '01.png', theme: 'ink', valign: 'flex-start', mainBottom: 900, bottom: { l: 'О нас · 1/9', ...next },
    mascot: { src: 'img/zubr-dumaet.png', h: 900, right: 140, bottom: 330, glow: true },
    blocks: [{ type: 'tag', text: 'О нас' }, { type: 'gap', s: 's' },
      { type: 'display', max: 120, lines: ['Сколько форумов', 'вы посетили', { t: 'за последний год?', c: 'acc' }] }] }),
  story({ out: '02.png', theme: 'paper', bottom: { l: 'О нас · 2/9', ...next },
    blocks: [{ type: 'display', lines: ['Два дня', 'речей.', 'Блокнот', 'конспектов.'] }, { type: 'gap', s: 'l' },
      { type: 'display', lines: [{ t: 'А в понедельник —', c: 'acc' }, { t: 'всё как было', c: 'acc' }] }] }),
  story({ out: '03.png', theme: 'ink', bottom: { l: 'О нас · 3/9', ...next },
    blocks: [{ type: 'p', html: 'Мы тоже через это проходили. И задали себе один вопрос:' }, { type: 'gap', s: 'l' },
      { type: 'display', lines: ['А что, если', 'форум будет', { t: 'про ваш бизнес,', c: 'acc' }, { t: 'а не про сцену?', c: 'acc' }] }] }),
  story({ out: '04.png', theme: 'amber', bottom: { l: 'О нас · 4/9', ...next },
    blocks: [{ type: 'tag', text: 'Так появился' }, { type: 'gap', s: 'm' },
      { type: 'display', lines: ['РЕШЕНО.', { t: 'Business Live', c: 'acc' }] }, { type: 'gap', s: 'l' },
      { type: 'p', html: 'Форум владельцев и руководителей спортивного бизнеса: школ, клубов, фитнеса, федераций и сервисов для спорта' }] }),
  story({ out: '05.png', theme: 'ink', bottom: { l: 'О нас · 5/9', ...next },
    blocks: [{ type: 'photo', h: 560, src: 'img/img6.jpg' }, { type: 'gap', s: 'm' },
      { type: 'display', max: 110, lines: ['Меньше докладов.', { t: 'Больше разборов', c: 'acc' }] }, { type: 'gap', s: 's' },
      { type: 'p', html: 'Business Live — бизнес разбирают перед залом. Hot Seat — вопросы, которые обычно не задают публично. <b>Owner Tables</b> — собственники в узком кругу' }] }),
  story({ out: '06.png', theme: 'paper', bottom: { l: 'О нас · 6/9', ...next },
    blocks: [{ type: 'photo', h: 560, src: 'img/img7.jpg' }, { type: 'gap', s: 'm' },
      { type: 'display', max: 120, lines: [{ t: '200–300', c: 'acc' }, 'человек.', 'Специально мало'] }, { type: 'gap', s: 's' },
      { type: 'p', html: 'Правильные люди в зале сильнее, чем тысячи случайных' }] }),
  story({ out: '07.png', theme: 'ink', valign: 'flex-start', mainBottom: 960, bottom: { l: 'О нас · 7/9', ...next },
    mascot: { src: 'img/zubr-networking.png', h: 640, right: 120, bottom: 330, glow: true },
    blocks: [{ type: 'tag', text: 'Business Match' }, { type: 'gap', s: 's' },
      { type: 'display', max: 95, lines: ['Приехать', 'не просто', 'знакомиться.', { t: 'Найти нужных', c: 'acc' }, { t: 'людей', c: 'acc' }] }] }),
  story({ out: '08.png', theme: 'paper', bottom: { l: 'О нас · 8/9', ...next },
    blocks: [{ type: 'photo', h: 560, src: 'img/img3.jpg' }, { type: 'gap', s: 'm' },
      { type: 'display', max: 110, lines: ['Приезжаете', 'с вопросом.', { t: 'Уезжаете', c: 'acc' }, { t: 'с планом', c: 'acc' }] }] }),
  story({ out: '09.png', theme: 'amber', valign: 'flex-start', mainBottom: 880, bottom: { l: 'reshenoforum.ru' },
    mascot: { src: 'img/zubr-priglashaet.png', h: 880, right: 60, bottom: 330 },
    blocks: [{ type: 'display', max: 120, lines: ['13–14 ноября', 'Москва'] }, { type: 'gap', s: 's' },
      { type: 'display', max: 110, lines: [{ t: 'Приехать решить', c: 'acc' }] }, { type: 'gap', s: 's' },
      { type: 'p', html: 'Ссылка — <b>в шапке профиля</b>' }] }),
];
